server:
  port: 5000
spring:
  profiles:
    active: @activatedProperties@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: ${PROD_DB_USERNAME}
    data-password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
mavit:
  app:
    jwtExpirationInMs: 86400000